### ISSUE TITLE
UCM2 documentation

### ISSUE THREAD

**Issue by perexg** [alsa-project/alsa-ucm-conf#103]
Add/improve the documentation for

- directory tree layout
- build-in string substitutions
- runtime conditional configuration selection
- mixer settings (boot -> use -> verb -> device)

**Comment by broukema** [comment]
Comments *within* the files to explain what the various parameters are for would help too. The PinePhone v1.2 has 50 alsa settings
````
$ sudo alsactl store -f - |grep "name " |wc
     50     258    1788
````
and many of the names are very similar to one another.

**Comment by perexg** [comment]
> Comments _within_ the files to explain what the various parameters are for would help too. The PinePhone v1.2 has 50 alsa settings

Not possible. Only driver developers knows the specific controls and the ASoC tree does not follow any conventions. So, if you want to know more - contact specific driver developers or study hardware.

The documentation is available at: https://www.alsa-project.org/alsa-doc/alsa-lib/group__ucm__conf.html

**Comment by broukema** [comment]
@perexg Since you agree that https://www.alsa-project.org/alsa-doc/alsa-lib/group__ucm__conf.html is a key start to the documentation, what is the objection to the merge request https://github.com/alsa-project/alsa-ucm-conf/pull/366/files , of which the main effect is to add a link to specifically that URL?

Independently:

I assume that ASoC means _Allwinner System on a Chip_ .

I personally am unlikely to look for more info on the 50 PP alsa parameters. But others who have problems are likely to, and few are likely to be willing to become hardware or driver experts. Maybe some will. I guess it's up to those interested to do both the communication work and understand enough to propose within-dot-conf-file comments that are considered useful and clear enough that they can convince you.
