### ISSUE TITLE
MSI MAG X570S TOMAHAWK MAX WIFI - microphone + front audio panel not working

### ISSUE THREAD

**Issue by motomyslen** [alsa-project/alsa-ucm-conf#186]
The same issue was reported on many forums but I didn't see it reported here so I'm creating this topic for all people with this motherboard.
**Issues**
- rear mic-in/line-in not working, sound is working fine
- front panel detects devices but not sound, not mic

I tried with kernel 5.18 and pulseaudio 16.1 - nothing changed.

[alsa-info.txt](https://github.com/alsa-project/alsa-ucm-conf/files/9078972/alsa-info.txt)

**Comment by yhojann-cl** [comment]
Similar issue here:

- https://github.com/alsa-project/alsa-ucm-conf/issues/172
- https://bugs.launchpad.net/ubuntu/+source/alsa-driver/+bug/1978988

**Comment by motomyslen** [comment]
I have USB device with id `0db0:a073`. I tried with v1.2.7.2 but it didn't work.

**Comment by perexg** [comment]
Please, give a try with the latest UCM tree - there are massive ALC4080 changes. If something does not work, please, report it and try to locate the appropriate ALSA device / jack and volume control - https://github.com/alsa-project/alsa-ucm-conf/blob/master/ucm2/DEBUG.md  .

**Comment by chrtom** [comment]
MSI MEG X570S ACE MAX (with ALC4082) has the same issue. It has `0db0:a47c` as the USB device ID.

I was able to get the front audio panel working by following the recommendation by @perexg to give the latest UCM tree a try. I followed the instructions at https://github.com/alsa-project/alsa-ucm-conf/blob/master/ucm2/DEBUG.md

Then I edited the regular expression in the "If.realtek-alc4080" part of file "ucm2/USB-Audio.conf" as follows:

`# 0db0:a47c MSI MEG X570S Ace Max`
`Regex "USB((0414:a00e)|(0b05:(1996|1a(16|2[07])))|(0db0:(005a|151f|1feb|419c|82c7|a073|b202|a47c)))"`

Note the added `|a47c` at the end of the regular expression. The first line is actually just a comment.

To get it to work on my system (Ubuntu 22.04) I also had to change the first line of said file from `Syntax 6` to `Syntax 4`. I think this was necessary because I'm using the default ALSA system libraries, which are at version 1.2.6.1.

I now have sound on headphones plugged in the front panel. Not sure, if there is any substantial difference between ALC4080 and ALC4082 though?

**Comment by chrtom** [comment]
Add-on to my previous comment: Headphones work on front panel, stereo output works on rear panel. However, there is no longer the "Configuration" option under "Output Device" in the Gnome sound settings. So I cannot switch to 5.1 or 7.1 output. It seems some more work is necessary to get the ACL 4080/82 to work properly...

**Comment by foobers** [comment]
Same/similar problems with MAG X570S Torpedo Max here on Debian. 

Line-in/mic on rear and front panels do not work at all. 

Internal recording, e. g. with "gnome-sound-recorder" will only work, when both S/PDIF in (only input option) and out are chosen, so the generated sound signal is looped into the digital input port of the chip. 
Then you don't have any audio feedback/monitoring, of course, and the speakers remain silent.

This MSI board seems to turn out to be a failed investment.

**Comment by perexg** [comment]
Note that each ALC4080 USB soundcard may have a bit different UCM configuration per motherboard depending on the used firmware. The best way is to try the latest UCM configuration (see https://github.com/alsa-project/alsa-ucm-conf/blob/master/README.md and https://github.com/alsa-project/alsa-ucm-conf/blob/master/ucm2/DEBUG.md) and report back your problems using a separate issue per hardware, if something does not work.

**Comment by perexg** [comment]
> Add-on to my previous comment: Headphones work on front panel, stereo output works on rear panel. However, there is no longer the "Configuration" option under "Output Device" in the Gnome sound settings. So I cannot switch to 5.1 or 7.1 output. It seems some more work is necessary to get the ACL 4080/82 to work properly...

The latest alsa-lib (Syntax 6) should support the multichannel profiles. The latest UCM configuration does not support old libraries.

**Comment by perexg** [comment]
This issue is for multiple motherboard now. I'm closing it right now. I think that I gathered all USB IDs and they are in the latest UCM configuration files. Please, open a new issue, if you have some problems.
