### ISSUE TITLE
UCM file required for Multiple sound card scenario for Renoir APU

### ISSUE THREAD

**Issue by VijendarReddy** [alsa-project/alsa-ucm-conf#30]
We recently upstreamed PDM Driver for Renoir APU.

Renoir APU platform has Onboard DMIC + Southbridge AZ (HD Audio Endpoint) support.
When External Mic connected,  Device switching should happen from Internal DMIC to external Mic.

Need UCM file to support Multiple sound cards for Renoir APU. 

Alsa info link:  https://pastebin.ubuntu.com/p/4kprhDZYbg/

Created Ticket based on discussion on the below-mentioned thread.
https://www.alsa-project.org/pipermail/alsa-devel/2020-June/168527.html

**Comment by perexg** [comment]
One question - the acp driver is only for DMIC? Is this driver activated only when the hardware platform has DMIC?

I would suggest to export the connection between the HDA driver and ACP driver in the components string. The related HDA driver may add `drv-dmic:acp` string to the components string. The components string is managed via snd_component_add() function in kernel (ALSA core).

**Comment by VijendarReddy** [comment]
Currently, ACP driver implementation supports only DMIC. Renoir APU platform has onboard DMIC.
I didn't get your point.
Can you elaborate how to export the connection between HDA driver and ACP driver?

**Comment by perexg** [comment]
> Currently, ACP driver implementation supports only DMIC. Renoir APU platform has onboard DMIC.

Ok, thanks. But we need probably support both ways to connect the internal microphone (HDA codec and DMIC via ACP).

> I didn't get your point.
> Can you elaborate how to export the connection between HDA driver and ACP driver?

The user space (UCM) should be notified somehow that those two drivers are connected. We can do those checks based on PCI IDs or so, but it's better that the driver will export this information somehow.

The ALSA info structure (struct snd_ctl_card_info) has components field (string) which can contain additional information passed to the user space about the hardware or the driver configuration.

I just suggest to pass this extra information for Renoir APU (the analog HDA codec driver - ). See my previous comment for the suggested implementation.

Current info obtained from the kernel:

````
Card hw:1 'Generic_1'/'HD-Audio Generic at 0xfd4c0000 irq 112'
  Mixer name	: 'Realtek ALC257'
  Components	: 'HDA:10ec0257,17aa5083,00100001'
  Controls      : 17
  Simple ctrls  : 8
````

Proposed info:

````
  Components	: 'HDA:10ec0257,17aa5083,00100001 drv-dmic:acp'
````

With this updated information, UCM can parse the components string and identify that there's internal microphone controlled by another driver.

**Comment by perexg** [comment]
Pulseaudio patch to skip the DMIC ALSA soundcard using UCM configuration: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/305

The above commit https://github.com/alsa-project/alsa-lib/commit/d9c835d8045cb441470421527bd119c73865d67f defined the Linked UCM variable to tell the applications that the hw:X UCM card cannot be used as a standalone UCM card.

**Comment by perexg** [comment]
A test (probably broken at the moment, but the goal is visible):

https://github.com/alsa-project/alsa-ucm-conf/pull/31

**Comment by jason77-wang** [comment]
Tested the mr/305 + alsa-ucm-conf #31, now there is no acp sound card in the pulseaudio, and the dmic on the acp is bindig to hda sound card in the pulseaudio, everything works as expected. But there is still one issue, that is after plugging the external mic, it will not be active automatically, that is because the dmic and external mic belong to the same profile while different sources.

@perexg  maybe this mr could fix the auto switching issue, could you please take a look at it?
https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/295

**Comment by jason77-wang** [comment]
BTW, I found the sound card#0 (ati/amd hdmi sound card) is also covered by the ucm2 #31, but according to my test, the hdmi can't work in the pulseaudio, it can't detect plug/unplug in the pulseaudio.

**Comment by jason77-wang** [comment]
@perexg 
After changing the hdmi2/3's pcm number, the hdmi works well. Please refer to: https://github.com/alsa-project/alsa-ucm-conf/pull/31

And for auto-swtich issue, the mr !295 of pulseaudio could fix this issue (but this mr is not accepted by PA yet).

So for, looks like everything about audio works well on that amd renoir machine, but there is a big issue, after adding HDA-Intel.conf, all HDA machines will apply those ucms, this is a problem, first those HDA machines work pretty well and don't need those ucms, second HDA machines have many many configurations like linein lineout ..., those ucms can't cover all configurations.

So it is possible to improve the ucm to let the ucm only apply to the machines with renoir audio and don't affect other machines. If we could implement it, we could remove Hdmi.conf since hdmi belong to a standalone sound card, the pulseaudio could handle them well without ucm.

**Comment by perexg** [comment]
I tried to resolve this in dcef48f13d4f5db79b006755074940b94730a883 (master). Note that I assue that my configuration which correct the kernel module name will be accepted to kernel: https://lore.kernel.org/alsa-devel/MN2PR12MB44882B2936E59EF361C7A371F7920@MN2PR12MB4488.namprd12.prod.outlook.com/T/#mfffb7d42e623d433203c8554cd5a2adcb370beb5 .

**Comment by jason77-wang** [comment]
@perexg ,

With the new change above, is the "https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/305" still needed?

**Comment by perexg** [comment]
Yes, it is. It only suppress the error message (UCM verb is not defined for the acp soundcard), but I'm sure that users will report that as a problem. It's better to have this possibility for UCM.

**Comment by perexg** [comment]
All issues are resolved now for in the ucm configuration for this hardware now. Closing.
