### ISSUE TITLE
Mic not working on "ROG Strix Z790-A Gaming WIFI II" with ALC4080

### ISSUE THREAD

**Issue by luluonino** [alsa-project/alsa-ucm-conf#431]
I ran into this issue https://github.com/alsa-project/alsa-ucm-conf/issues/394 while searching about exactly the same problem on "ROG Strix Z790-A Gaming WIFI II". The commit included in issue 394 fixed the speaker on my headphone plugged into the case front panel. But the mic still doesn't work. It is detected as "Microphone - USB Audio" but it doesn't pick up any sound. 

I'm running Ubuntu 24.04 and with alsa-ucm-conf-1.2.12 applied. Here is the alsa-info dump. Note after applying the fix in issue 394, the audio codec is still detected as generic USB audio but there is indeed sound afterwards. 
[alsa-info.txt](https://github.com/user-attachments/files/16136523/alsa-info.txt)

I've tried all potential solutions I could find online but none worked. Any help is greatly appreciated!

**Comment by luluonino** [comment]
After a bit more testing, I found that the mic actually does pick up some sound, but too quiet even if I should to it. It's probably a different problem. I'm going to close this issue. If anyone finds this issue because of the same problem. Don't apply the newest release of alsa-ucm-conf but instead apply the exact change as in issue 394. Your other alsa libraries might not be compatible with the newest release of alsa-ucm-conf.

**Comment by ermanuzun82** [comment]
> After a bit more testing, I found that the mic actually does pick up some sound, but too quiet even if I should to it. It's probably a different problem. I'm going to close this issue. If anyone finds this issue because of the same problem. Don't apply the newest release of alsa-ucm-conf but instead apply the exact change as in issue 394. Your other alsa libraries might not be compatible with the newest release of alsa-ucm-conf.

Hello luluonino,

I have rog strix z790-E Gaming wifi II motherboard.
I am terribly sorry to buy this motherboard because I am having sound and microphone problem from the front panel too.
I am able to make the microphone working, the other side can hear me, but also they say, we are hearing everything on the computer which I use. For ex: netflix or youtube.

I tried everything bios update, removing the drivers, all sound settings on windows 11. Nothing worked.
And also when I am speaking on the mic, the microphone sound bar does not increase like It's perfectly working. You can check this from control panel, sound, recording device.

I don't understand where the problem really is. Also sometimes, when windows11 is loading there is a strange noise is coming like SSSHHHHHHHH deep sound, and when the windows 11 logins, the noise is gone. I am going to be crazy.
Can you help me?

**Comment by luluonino** [comment]
Hi @ermanuzun82 , sorry I had only Ubuntu installed on this machine and couldn't test it in Windows 11. But my impression is it works out-of-the-box for Windows because that's what's officially supported for these motherboards. This Z790-E motherboard has the same ALC4080 codec. Also just for your information, blue tooth headphones seem to work just fine. It's only the front panel audio jack that is having issues for me.

**Comment by ermanuzun82** [comment]
Thank you for the reply :) When I read different statements on google results, I see that there are many people like me who is suffering from the front panel issue. 
Today, I wrote to Asus, lets see, what they will give as an answer.

**Comment by Apteryks** [comment]
> After a bit more testing, I found that the mic actually does pick up some sound, but too quiet

I have exactly the same problem with the Asus ROG STRIX B650E-I GAMING WIFI motherboard boasting the same Realtek ALC4080 chip.  Could you pinpointed what was the issue, by luck?

**Comment by luluonino** [comment]
@Apteryks I've been using a Bluetooth headphone since. Didn't try to dig deeper.

**Comment by Apteryks** [comment]
OK! I'll make sure to share something here if I discover something useful.
